### Python
---------------------------------------------------------------------------------------------------------
Follow me on <img src="./imgs/linkedinlogo.png" width=24 height=24> [Sumit Khanna](https://www.linkedin.com/in/sumitkhanna/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3BPJFykAjJT8%2BIv%2ByTX%2F1jOA%3D%3D) for more updates 


## Numpy CheatSheet

In [28]:
import numpy as np

### Core Functions


In [29]:
# np.array
data = [1, 2, 3, 4]
arr = np.array(data)
print("Array from list:", arr)

Array from list: [1 2 3 4]


In [30]:
# np.arange
arr_range = np.arange(10, 20, 2)
print("Array with range:", arr_range)

Array with range: [10 12 14 16 18]


In [31]:
# np.zeros, np.ones
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((3, 2))
print("Zeros array:\n", zeros_arr)
print("Ones array:\n", ones_arr)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [32]:
# np.eye (Identity Matrix)
identity_matrix = np.eye(4)
print("Identity matrix:\n", identity_matrix)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
# np.random.rand, np.random.randn
rand_arr = np.random.rand(2, 3)
randn_arr = np.random.randn(3, 2)
print("Random uniform array:\n", rand_arr)
print("Random normal array:\n", randn_arr)

Random uniform array:
 [[0.72859265 0.00167948 0.09512196]
 [0.34262591 0.02179833 0.69628906]]
Random normal array:
 [[ 1.07851527 -0.25913882]
 [-0.27601988 -0.00366866]
 [-0.08370633  0.13587723]]


In [34]:
# np.linspace
lin_arr = np.linspace(0, 10, 6)
print("Linearly spaced array:", lin_arr)

Linearly spaced array: [ 0.  2.  4.  6.  8. 10.]


### Shape and Size

In [35]:
print("Shape of rand_arr:", rand_arr.shape)
print("Dimensions of rand_arr:", rand_arr.ndim)
print("Total elements in rand_arr:", rand_arr.size)

Shape of rand_arr: (2, 3)
Dimensions of rand_arr: 2
Total elements in rand_arr: 6


In [36]:
# Reshaping
reshaped_arr = rand_arr.reshape(3, 2)
print("Reshaped array:\n", reshaped_arr)

Reshaped array:
 [[0.72859265 0.00167948]
 [0.09512196 0.34262591]
 [0.02179833 0.69628906]]


In [37]:
# Flattening
flattened_arr = reshaped_arr.flatten()
print("Flattened array:", flattened_arr)


Flattened array: [0.72859265 0.00167948 0.09512196 0.34262591 0.02179833 0.69628906]


In [38]:
# Transpose
transposed_arr = rand_arr.T
print("Transposed array:\n", transposed_arr)

Transposed array:
 [[0.72859265 0.34262591]
 [0.00167948 0.02179833]
 [0.09512196 0.69628906]]


### Element-wise Operations

In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Addition:", np.add(arr1, arr2))
print("Subtraction:", np.subtract(arr1, arr2))
print("Multiplication:", np.multiply(arr1, arr2))
print("Division:", np.divide(arr1, arr2))
print("Exponentiation:", np.power(arr1, arr2))

# More math functions
arr3 = np.array([0.5, 1.5, 2.5])
print("Square root:", np.sqrt(arr3))
print("Exponential:", np.exp(arr3))
print("Logarithm:", np.log(arr3))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponentiation: [  1  32 729]
Square root: [0.70710678 1.22474487 1.58113883]
Exponential: [ 1.64872127  4.48168907 12.18249396]
Logarithm: [-0.69314718  0.40546511  0.91629073]


### Statistics

In [40]:
data = np.array([22, 87, 5, 43, 56, 73, 55, 54, 11, 20, 51, 5, 79, 31, 27])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Min:", np.min(data))
print("Max:", np.max(data))
print("Sum:", np.sum(data))

Mean: 41.266666666666666
Median: 43.0
Standard Deviation: 25.647525330049984
Variance: 657.7955555555556
Min: 5
Max: 87
Sum: 619


### Core Array Creation and Manipulation 

In [41]:
# np.empty: Creates an array without initializing entries
empty_arr = np.empty((2, 3))
print("Empty array:\n", empty_arr)

Empty array:
 [[0.72859265 0.34262591 0.00167948]
 [0.02179833 0.09512196 0.69628906]]


In [42]:
# np.full: Creates an array filled with a specific value
full_arr = np.full((3, 2), 7)
print("Array filled with 7:\n", full_arr)

Array filled with 7:
 [[7 7]
 [7 7]
 [7 7]]


In [43]:
# np.concatenate: Joins arrays along an existing axis
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
concat_arr = np.concatenate((arr1, arr2), axis=0)  # Join vertically
print("Concatenated array:\n", concat_arr)

Concatenated array:
 [[1 2]
 [3 4]
 [5 6]]


In [44]:
# np.vstack, np.hstack: Stack arrays vertically or horizontally
vstack_arr = np.vstack((arr1, arr2))
hstack_arr = np.hstack((arr1, arr2.T))  # Need to transpose arr2 for compatibility
print("Vertically stacked:\n", vstack_arr)
print("Horizontally stacked:\n", hstack_arr)

Vertically stacked:
 [[1 2]
 [3 4]
 [5 6]]
Horizontally stacked:
 [[1 2 5]
 [3 4 6]]


In [45]:
# np.split: Splits an array into multiple sub-arrays
split_arr = np.split(arr1, 2, axis=1)  # Split into 2 columns
print("Split arrays:\n", split_arr)

Split arrays:
 [array([[1],
       [3]]), array([[2],
       [4]])]


In [46]:
# np.tile: Constructs an array by repeating a given array
tiled_arr = np.tile(arr1, (2, 3))  # Repeat arr1 2 times vertically and 3 times horizontally
print("Tiled array:\n", tiled_arr)

Tiled array:
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


### Linear Algebra


In [47]:
# np.dot: Dot product of two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(arr1, arr2)
print("Dot product:\n", dot_product)

Dot product:
 [[19 22]
 [43 50]]


In [48]:
# np.linalg.inv: Matrix inverse
inv_arr = np.linalg.inv(arr1)
print("Inverse of arr1:\n", inv_arr)

Inverse of arr1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [49]:
# np.linalg.det: Matrix determinant
det_arr = np.linalg.det(arr1)
print("Determinant of arr1:", det_arr)

Determinant of arr1: -2.0000000000000004


In [50]:
# np.linalg.eig: Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(arr1)
print("Eigenvalues of arr1:", eigenvalues)
print("Eigenvectors of arr1:\n", eigenvectors)


Eigenvalues of arr1: [-0.37228132  5.37228132]
Eigenvectors of arr1:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [51]:
# np.trace: Sum of diagonal elements
trace = np.trace(arr1)
print("Trace of arr1:", trace)

Trace of arr1: 5


### Calculus and Fourier Transform

In [52]:
# np.gradient: Numerical gradient (finite differences)
x = np.array([1, 2, 4, 7, 11, 16])
y = np.array([1, 3, 9, 19, 31, 49])
gradient = np.gradient(y, x) 
print("Gradient:", gradient)

Gradient: [2.         2.33333333 3.13333333 3.19047619 3.26666667 3.6       ]


In [53]:
# np.fft.fft: Discrete Fourier Transform
x = np.array([1.0, 1.0, 1.0, 1.0, 1.0])
y = np.fft.fft(x)
print("FFT:", y)

FFT: [5.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


### Probability

In [54]:
# np.random.choice: Randomly sample elements from an array
elements = np.array(['A', 'B', 'C', 'D'])
probabilities = [0.1, 0.4, 0.2, 0.3]
sample = np.random.choice(elements, size=5, p=probabilities)  # Sample 5 elements
print("Random sample:", sample)

Random sample: ['B' 'D' 'B' 'B' 'D']


---------------------------------------------------------------------------------------------------------
Follow me on <img src="./imgs/linkedinlogo.png" width=24 height=24> [Sumit Khanna](https://www.linkedin.com/in/sumitkhanna/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3BPJFykAjJT8%2BIv%2ByTX%2F1jOA%3D%3D) for more updates 